<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace>BizFirst.Integration.Hedera.Domain</RootNamespace>
    <AssemblyName>BizFirst.Integration.Hedera.Domain</AssemblyName>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>1591</NoWarn>
  </PropertyGroup>
</Project>
